[package]
name = "piano"
version = "0.1.0"
description = "Practise piano from sheet music with a MIDI keyboard"
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "piano_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri = { version = "2.11.5", features = [] }
tauri-plugin-dialog = "2.7.0"
tauri-plugin-midi = "0.2.0"
tauri-plugin-sql = { version = "2.4.0", features = ["sqlite"] }

[dev-dependencies]
tempfile = "3"
