// Written by `cargo test` in src-tauri.
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Creates the library folder, parents included. Already existing is success, so onboarding and a
	 *  later folder change both call it without checking first.
	 */
	ensureDir: (path: string) => __TAURI_INVOKE<null>("ensure_dir", { path }),
	/**  Every setting the window starts from, in one read. */
	settingsRead: () => __TAURI_INVOKE<{ [key in string]: unknown }>("settings_read"),
	/**
	 *  One setting. A key the sound engine owns goes on the running engine first, so a value the
	 *  engine refuses is answered with its reason and never stored.
	 */
	settingsWrite: (key: string, value: unknown) => __TAURI_INVOKE<null>("settings_write", { key, value }),
	/**  Every piece whose file is in the folder. A missing file hides its piece until it is back. */
	pieceList: (sort: string) => __TAURI_INVOKE<PieceRow[]>("piece_list", { sort }),
	/**
	 *  The path of every piece whose file is in the folder, whatever the list pane is filtered to. The
	 *  finder reads it to know which of its rows are already downloaded.
	 */
	piecePaths: () => __TAURI_INVOKE<string[]>("piece_paths"),
	pieceGet: (path: string) => __TAURI_INVOKE<{
	path: string,
	title: string | null,
	composer: string | null,
	measure_count: number | null,
	duration_s: number | null,
	midi_lo: number | null,
	midi_hi: number | null,
	has_tempo: number | null,
	constant_tempo: number | null,
	key_sharps: number | null,
	key_mode: string | null,
	part_count: number | null,
	part_name: string | null,
	favorite: number,
	error: string | null,
	/**  Piece settings. NULL in any of them means the piece has never been given that one. */
	tempo_mode: string | null,
	tempo_value: number | null,
	metronome: number | null,
	count_in_bars: number | null,
	hands: string | null,
	mode: string | null,
	loop: number | null,
	section_from: number | null,
	section_to: number | null,
	/**  Played tick the practice was left at, which is where the piece reopens. NULL is its start. */
	position_tick: number | null,
	best_grade: number | null,
	last_played: number | null,
	practised_s: number | null,
} | null>("piece_get", { path }),
	/**  Stores what the play screen just changed. */
	pieceUpdateSettings: (path: string, values: { [key in string]: unknown }) => __TAURI_INVOKE<null>("piece_update_settings", { path, values }),
	/**
	 *  Stores where the play screen left the cursor, in played ticks. It is state of the piece rather
	 *  than a setting: no control shows it and no play reads it out of its settings.
	 */
	pieceUpdatePosition: (path: string, tick: number) => __TAURI_INVOKE<null>("piece_update_position", { path, tick }),
	/**  The one thing the library writes about a piece. */
	pieceSetFavorite: (path: string, favorite: boolean) => __TAURI_INVOKE<null>("piece_set_favorite", { path, favorite }),
	/**  The last plays of a piece, newest first: the History ledger of the detail pane. */
	pieceRecentPlays: (path: string, limit: number) => __TAURI_INVOKE<PlayRow[]>("piece_recent_plays", { path, limit }),
	/**  Stores one finished play. Nothing on screen announces it. */
	playInsert: (path: string, kind: string, startedAt: number | null, durationS: number | null) => __TAURI_INVOKE<null>("play_insert", { path, kind, startedAt, durationS }),
	/**  Stores one complete performance. A run with nothing to grade leaves the grade columns empty. */
	performanceInsert: (path: string, run: Performance) => __TAURI_INVOKE<null>("performance_insert", { path, run }),
	/**
	 *  The files whose bytes the window must parse: the library folder walked, or the one file at
	 *  `path` looked at, against the rows. A row whose file came back untouched is restored here and a
	 *  row whose file is gone is hidden here, so the window is left with the parsing alone.
	 */
	indexPlan: (folder: string, path: string | null) => __TAURI_INVOKE<FileEntry[]>("index_plan", { folder, path }),
	/**  Writes a fresh index. The row's favorite, settings and history survive, and any error clears. */
	indexUpsert: (path: string, index: PieceIndex, mtime: number, size: number) => __TAURI_INVOKE<null>("index_upsert", { path, index, mtime, size }),
	/**  A file the app cannot read stays a piece: it gains the reason and keeps its old index columns. */
	indexMarkError: (path: string, error: string, mtime: number, size: number) => __TAURI_INVOKE<null>("index_mark_error", { path, error, mtime, size }),
	/**  Drops the piece, and its plays with it through the foreign key that cascades. */
	pieceDelete: (path: string) => __TAURI_INVOKE<null>("piece_delete", { path }),
	/**
	 *  Builds the graph, starts it on the output device and puts the stored settings back on it. Each
	 *  setting is applied whatever the one before it did, so an unplugged device does not cost the app
	 *  its effect chain; only a failed start stops the rest.
	 */
	audioStart: () => __TAURI_INVOKE<null>("audio_start"),
	audioStatus: () => __TAURI_INVOKE<AudioStatus>("audio_status"),
	/**
	 *  One metronome click, at a volume of 0 to 100. A no-op where there is no engine, so the
	 *  metronome is simply silent there.
	 */
	audioClick: (strength: string, volume: number) => __TAURI_INVOKE<void>("audio_click", { strength, volume }),
	/**
	 *  One note the app plays rather than the player: the inactive hand sounding itself. It takes the
	 *  same path a MIDI key takes, so the velocity curve is on it, unless `raw` says the caller already
	 *  holds an output velocity. A no-op where there is no engine.
	 */
	audioNote: (midi: number, velocity: number, on: boolean, raw: boolean) => __TAURI_INVOKE<void>("audio_note", { midi, velocity, on, raw }),
	/**  Every Audio Unit effect installed on the machine, Apple's own included. */
	audioEffects: () => __TAURI_INVOKE<Effect[]>("audio_effects"),
	audioChain: () => __TAURI_INVOKE<EffectSlot[]>("audio_chain"),
	/**
	 *  Opens one slot's plugin window. Closing it emits `audio-chain-changed` with the whole chain,
	 *  which is how the plugin's settings reach the setting the webview keeps.
	 */
	audioShowEffect: (index: number) => __TAURI_INVOKE<null>("audio_show_effect", { index }),
	/**
	 *  Every device the app can play through, newest list each call. The webview reads it again on
	 *  every `audio-devices-changed`.
	 */
	audioOutputDevices: () => __TAURI_INVOKE<OutputDevice[]>("audio_output_devices"),
	/**
	 *  Every instrument the engine can play: Logic's pianos, the files in the folder the webview
	 *  names, and the installed Audio Unit instruments.
	 */
	audioInstruments: (folder: string) => __TAURI_INVOKE<Instrument[]>("audio_instruments", { folder }),
	/**
	 *  Loads one of them, with the state a plugin was last left in, the Envelope kept for it and the
	 *  level of every Role that was moved, and answers the engine's status. The engine builds the
	 *  instrument with nothing locked, so a key pressed meanwhile plays on the one still in.
	 */
	audioLoadInstrument: (id: string) => __TAURI_INVOKE<AudioStatus>("audio_load_instrument", { id }),
	/**
	 *  Takes the loaded instrument out, so the app makes no sound until one is chosen again, and
	 *  answers the engine's status, which now names no instrument.
	 */
	audioUnloadInstrument: () => __TAURI_INVOKE<AudioStatus>("audio_unload_instrument"),
	/**  Opens the instrument's own window, and answers with its state when the user closes it again. */
	audioShowInstrument: () => __TAURI_INVOKE<string | null>("audio_show_instrument"),
	/**
	 *  The envelope the loaded instrument answers a key with now. Null when a plugin is playing, which
	 *  is how the webview knows to offer no envelope for it, and null where there is no engine.
	 */
	audioEnvelope: () => __TAURI_INVOKE<{
	attack: number,
	decay: number,
	sustain: number,
	release: number,
} | null>("audio_envelope"),
	/**
	 *  Replaces it. The voice engine has it at the next buffer, and every note struck from there on
	 *  follows it; whatever is already sounding plays on unchanged.
	 */
	audioApplyEnvelope: (envelope: Envelope) => __TAURI_INVOKE<void>("audio_apply_envelope", { envelope }),
	/**
	 *  How loud one of the noises a piano makes around the tone sounds, 0 to 100: the damper landing,
	 *  the key coming back up, the strings ringing along, the pedal. 0 sounds none of it, the tone
	 *  itself has no level, and a role the loaded instrument has no samples for is simply silent. What
	 *  a slider sends as it moves; a load puts the kept levels on by itself.
	 */
	audioApplyRoleLevel: (role: Role, percent: number) => __TAURI_INVOKE<void>("audio_apply_role_level", { role, percent }),
	/**  The Preview's note list, in seconds at the score's own tempo. Replaces whatever was loaded. */
	previewLoad: (notes: PreviewNote[]) => __TAURI_INVOKE<void>("preview_load", { notes }),
	previewPlay: () => __TAURI_INVOKE<void>("preview_play"),
	previewPause: () => __TAURI_INVOKE<void>("preview_pause"),
	/**  Jumps to a time in the piece's own seconds, tempo percent aside. */
	previewSeek: (seconds: number | null) => __TAURI_INVOKE<void>("preview_seek", { seconds }),
	/**  The tempo as a percent of the score's own: 50 makes the piece take twice as long. */
	previewRate: (percent: number) => __TAURI_INVOKE<void>("preview_rate", { percent }),
	/**  Stops, forgets the note list and returns to the start. What leaving the Preview sends. */
	previewStop: () => __TAURI_INVOKE<void>("preview_stop"),
	midiStatus: () => __TAURI_INVOKE<MidiPorts>("midi_status"),
	/**
	 *  The rule the ports follow: listen on the pinned port alone, or on every port outside the hidden
	 *  list when nothing is pinned. The webview owns both, out of the session and the settings, and
	 *  sends them whole at every change.
	 */
	midiListen: (pinned: string | null, hidden: string[]) => __TAURI_INVOKE<void>("midi_listen", { pinned, hidden }),
	/**
	 *  Copies an imported file into the library folder, overwriting whatever is at `dst`. The stamp of
	 *  the written file goes back so the caller can index it without listing the folder again.
	 */
	copyFile: (src: string, dst: string) => __TAURI_INVOKE<Stamp>("copy_file", { src, dst }),
	/**  Every score file under the library folder, at any depth, in no particular order. */
	listLibrary: (folder: string) => __TAURI_INVOKE<FileEntry[]>("list_library", { folder }),
	/**  The bytes of one file. */
	readFile: (path: string) => __TAURI_INVOKE<unknown>("read_file", { path }),
	/**
	 *  Deletes the finder's download once the import has read it: a file the user never saw does not
	 *  belong in the Trash. Nothing outside the OS temp directory is deleted, so the Trash stays the
	 *  only way a file of the library folder goes.
	 */
	removeTempFile: (path: string) => __TAURI_INVOKE<null>("remove_temp_file", { path }),
	/**
	 *  Opens the file's folder in the Finder with the file selected. A file that has gone since the
	 *  last scan is a reason the caller shows, not a silent no-op.
	 */
	revealInFinder: (path: string) => __TAURI_INVOKE<null>("reveal_in_finder", { path }),
	/**
	 *  Moves the file to the system Trash, which is the only undo a delete has. On macOS `NSFileManager`
	 *  does the move instead of the Finder, so deleting never asks the user for automation rights; the
	 *  cost is that the Trash may not offer "Put Back" for the file.
	 * 
	 *  A file that is already gone is answered as gone: the trash crate words that failure the way it
	 *  words every other one, and the library page drops the piece row on this kind alone.
	 */
	trashFile: (path: string) => __TAURI_INVOKE<null>("trash_file", { path }),
	/**
	 *  The scan is one blocking pass over the whole index, and the first call waits for `warm()` to
	 *  finish building it, so it runs on a blocking thread and leaves the runtime to the file commands.
	 */
	finderSearch: (query: string, pdmx: boolean) => __TAURI_INVOKE<SearchResult>("finder_search", { query, pdmx }),
	/**
	 *  Fetches or unzips one row into a temp file and answers with its path. Nothing reaches the
	 *  library folder from here; the import path a dropped file takes does that.
	 */
	finderDownload: (row: FinderRow) => __TAURI_INVOKE<string>("finder_download", { row }),
	/**  Whether the tarball is unpacked, which is the one thing the finder needs to deliver a PDMX row. */
	pdmxStatus: () => __TAURI_INVOKE<boolean>("pdmx_status"),
	/**
	 *  Downloads the tarball into the PDMX folder. The archive never reaches the disk: it is unpacked
	 *  as it arrives.
	 * 
	 *  The error is one short line for the settings dialog to show: `already downloading`,
	 *  `no data folder`, `no connection`, `Zenodo answered <status>`, `not enough disk space`,
	 *  `download stopped`, or `cancelled` when the user stopped it.
	 */
	pdmxFetch: (progress: Channel<PdmxProgress>) => __TAURI_INVOKE<null>("pdmx_fetch", { progress }),
	/**  Stops the running fetch, which then removes what it had unpacked. */
	pdmxCancel: () => __TAURI_INVOKE<void>("pdmx_cancel"),
	/**  The version this build was made as, which the status bar shows. */
	appVersion: () => __TAURI_INVOKE<string>("app_version"),
	/**  The version waiting on the release page, or nothing when this build is the newest. */
	updateCheck: () => __TAURI_INVOKE<string | null>("update_check"),
	/**
	 *  Fetches the newer bundle and swaps the app on disk. Nothing restarts, so the new version starts
	 *  at the next launch and a practice session is never cut short.
	 */
	updateInstall: () => __TAURI_INVOKE<null>("update_install"),
	/**
	 *  Starts the app again, which is how a version already on disk takes over. This never returns:
	 *  the process is replaced by a fresh one.
	 */
	updateRestart: () => __TAURI_INVOKE<void>("update_restart"),
};

/** Events */
export const events = {
	audioChainChanged: makeEvent<AudioChainChanged>("audio-chain-changed"),
	audioDevicesChanged: makeEvent<AudioDevicesChanged>("audio-devices-changed"),
	audioLoad: makeEvent<Meter>("audio-load"),
	midiPedal: makeEvent<Pedal>("midi-pedal"),
	midiPorts: makeEvent<MidiPorts>("midi-ports"),
	midiStrike: makeEvent<StrikeEvent>("midi-strike"),
	previewProgress: makeEvent<PreviewProgress>("preview-progress"),
};

/* Types */
/**
 *  Carries the whole effect chain, as `audio_chain` would answer it, whenever the engine changes
 *  it: what the webview writes back to the setting it keeps.
 */
export type AudioChainChanged = EffectSlot[];

/**
 *  Tells the webview its device list is stale. Sent when CoreAudio reports a device plugged in or
 *  unplugged, so the picker follows the hardware without a restart.
 */
export type AudioDevicesChanged = null;

/**
 *  What the Audio dialog reads: whether sound can come out of the app, the one line saying why not
 *  when it cannot, and the output the engine plays through.
 */
export type AudioStatus = {
	available: boolean,
	reason: string,
	/**  Opaque id of the device the engine plays through now; null while it plays through none. */
	device: string | null,
	device_name: string,
	/**
	 *  What the engine is playing through now; empty when nothing is loaded, which is one of the
	 *  reasons above. The mixer names it beside the device.
	 */
	instrument: string,
	/**  Why the device playing is not the one chosen; empty while the choice is honoured. */
	fallback: string,
	buffer_frames: number,
	/**
	 *  The buffer sizes the device playing takes, of the ones the dialog knows, ascending. Empty
	 *  where there is no engine and no device.
	 */
	buffer_choices: number[],
	sample_rate: number,
	/**
	 *  The rate the loaded instrument's samples were recorded at, which the engine plays them as
	 *  they are at; 0 for a plugin, which renders at any rate, and while nothing is loaded.
	 */
	instrument_rate: number,
	/**
	 *  What the device reports the buffer costs: its own latency, the safety offset, the stream
	 *  and the buffer itself, at the rate the device runs.
	 */
	latency_ms: number,
	/**
	 *  The noises around the tone the loaded instrument offers, each of them a toggle the webview
	 *  keeps for it. Empty for a plugin and for a file that has none of them.
	 */
	roles: Role[],
};

/**  One effect the machine has installed, as the Add menu lists it. */
export type Effect = {
	/**  Opaque to the webview, and the same string on every Mac that has the plugin. */
	id: string,
	name: string,
	manufacturer: string,
};

/**
 *  One place in the effect chain. The webview keeps the whole list as one global setting and hands
 *  it back whole; `missing` is the engine's answer, not the webview's to send.
 */
export type EffectSlot = {
	id: string,
	/**  What the plugin was called when it was last seen, which is how a missing slot is named. */
	name?: string,
	bypass?: boolean,
	/**  The plugin's own settings: its property list, base64 so it is a plain string in JSON. */
	state?: string,
	/**
	 *  Whether the plugin is not installed on this machine, in which case the slot keeps its place
	 *  and its state but makes no sound.
	 */
	missing?: boolean,
};

/**
 *  How a sampler instrument's loudness answers a key: seconds to reach full loudness, seconds to
 *  fall from there, the fraction of full loudness a held note settles at, and seconds to fade once
 *  the key comes up. Only the sampler has one; a hosted plugin shapes its notes in its own window.
 */
export type Envelope = {
	attack: number,
	decay: number,
	sustain: number,
	release: number,
};

/**
 *  One score file of the library folder. `rel_path` is the piece's identity, `mtime` (milliseconds)
 *  and `size` say whether it changed since it was indexed.
 */
export type FileEntry = {
	relPath: string,
	mtime: number,
	size: number,
};

/**  One search hit, with everything the finder's two lines show and the name the file lands under. */
export type FinderRow = {
	provider: Provider,
	/**  Composer heading, shared by both providers after normalisation ("Frédéric Chopin"). */
	heading: string,
	title: string,
	opus: string | null,
	number: string | null,
	movement: number | null,
	movementName: string | null,
	key: string | null,
	time: string | null,
	bars: number | null,
	ratings: number,
	/**  The uploader's own title when it differs from the site's title field. */
	alt: string | null,
	/**  KernScores download URL, or the PDMX path under `<pdmx folder>/mxl/`. */
	file: string,
	fileName: string,
};

export type Grade = {
	grade: number | null,
	expected: number,
	matched: number,
	extras: number,
	meanTiming: number | null,
	meanVelocity: number | null,
	meanRelease: number | null,
};

/**
 *  One line of the instrument picker. The id is opaque: a file and an Audio Unit look the same
 *  from the webview, which only ever hands one back.
 */
export type Instrument = {
	id: string,
	name: string,
	/**
	 *  `file` for one the sampler loads, `plugin` for a hosted Audio Unit, which is the one that
	 *  has a window of its own.
	 */
	kind: string,
	loaded: boolean,
	/**  Why this instrument is not sounding, when it is the chosen one and its load failed. */
	reason: string,
};

/**  What happened, as far as the window may act on it. */
export type Kind = 
/**  The file the command was asked about is no longer there. */
"gone" | 
/**  A rule of the app or the sound engine said no, and the text is its reason. */
"refused" | 
/**  Anything else, with what the OS or a library reported as the text. */
"failed";

/**
 *  What the render block last cost: the voices sounding, the most it may hold at once, and the
 *  block's own time as a percent of the time the buffer it filled plays for.
 */
export type Meter = {
	voices: number,
	limit: number,
	load: number,
};

/**
 *  One MIDI input port as the settings dialog lists it. The id is stable across a re-plug, so a
 *  pinned keyboard is the same keyboard when it comes back.
 */
export type MidiPort = {
	id: string,
	name: string,
};

/**
 *  What the webview's MIDI module shows: the ports being listened to, every port the machine has,
 *  the one port pinned if there is one, and the one line saying why there is no MIDI at all.
 */
export type MidiPorts = {
	devices: string[],
	ports: MidiPort[],
	pinned: string | null,
	error: string | null,
};

/**
 *  One output device as the picker lists it. The system default is not a row here; the dialog
 *  offers it as the choice of no device at all.
 */
export type OutputDevice = {
	id: string,
	name: string,
};

/**  How far the download has come; `total` is absent when the server sends no `Content-Length`. */
export type PdmxProgress = {
	done: number,
	total: number | null,
};

/**  A sustain pedal move, 0 to 127 as the pedal sent it. */
export type Pedal = {
	value: number,
};

/**  One complete performance: what it ran at, then what it earned. */
export type Performance = {
	startedAt: number | null,
	seconds: number | null,
	tempoMode: string,
	tempoValue: number | null,
	hands: string,
	/**  Null when the run asked nothing of the player, so there was nothing to grade. */
	grade: Grade | null,
};

/**  A piece's summary as indexing produced it. */
export type PieceIndex = {
	title: string,
	composer: string,
	measureCount: number,
	durationS: number | null,
	midiLo: number,
	midiHi: number,
	hasTempo: boolean,
	constantTempo: boolean,
	keySharps: number,
	keyMode: string,
	partCount: number,
	partName: string,
};

/**  A piece as the library page reads it: its index columns, its file facts and its history. */
export type PieceRow = {
	path: string,
	title: string | null,
	composer: string | null,
	measure_count: number | null,
	duration_s: number | null,
	midi_lo: number | null,
	midi_hi: number | null,
	has_tempo: number | null,
	constant_tempo: number | null,
	key_sharps: number | null,
	key_mode: string | null,
	part_count: number | null,
	part_name: string | null,
	favorite: number,
	error: string | null,
	/**  Piece settings. NULL in any of them means the piece has never been given that one. */
	tempo_mode: string | null,
	tempo_value: number | null,
	metronome: number | null,
	count_in_bars: number | null,
	hands: string | null,
	mode: string | null,
	loop: number | null,
	section_from: number | null,
	section_to: number | null,
	/**  Played tick the practice was left at, which is where the piece reopens. NULL is its start. */
	position_tick: number | null,
	best_grade: number | null,
	last_played: number | null,
	practised_s: number | null,
};

/**  One play of a piece, as the History ledger reads it. A practice leaves the last columns NULL. */
export type PlayRow = {
	id: number,
	kind: string,
	started_at: number,
	duration_s: number,
	tempo_mode: string | null,
	tempo_value: number | null,
	hands: string | null,
	grade: number | null,
};

/**  One note of the Preview, as the webview built it from the Score. */
export type PreviewNote = {
	midi: number,
	velocity: number,
	/**  Seconds from the start of the piece at the score's own tempo. */
	on: number | null,
	off: number | null,
};

/**
 *  Where Preview playback stands, sent about thirty times a second and once more when the piece
 *  ends, with `playing` false and the time back at zero.
 */
export type PreviewProgress = {
	seconds: number,
	playing: boolean,
};

export type Provider = "KernScores" | "PDMX";

/**  The window switches on the kind and shows the text; it never reads the text to decide anything. */
export type Refusal = {
	kind: Kind,
	text: string,
};

/**
 *  What a zone is for: the tone a key-down sounds, or one of the noises a piano makes around it.
 *  Every role but `Sustain` sounds at a level the user sets, 0 being silent.
 */
export type Role = 
/**  The tone itself, on key-down. */
"sustain" | 
/**  The damper falling back on the string, on key-up. */
"release" | 
/**  The key itself coming back up, on key-up. */
"key_off" | 
/**  The other strings ringing along, on key-down while the pedal is down. */
"sympathetic" | 
/**  The pedal going down and coming up. */
"pedal_noise";

export type SearchResult = {
	rows: FinderRow[],
	/**  Matches beyond the 30 rows returned. */
	more: number,
};

/**  What a file was when it was last read: enough to tell whether it changed. */
export type Stamp = {
	mtime: number,
	size: number,
};

/**  One strike as the play engine reads it, and as the webview has always received it. */
export type StrikeEvent = {
	midi: number,
	velocity: number,
	/**  Unix milliseconds, the timeline `performance.timeOrigin + performance.now()` runs on. */
	time: number,
	on: boolean,
};

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

